### ISSUE TITLE
Set-up the web applications page to look similar to the information gathering page

### ISSUE THREAD

**Issue by giga1699** [pwnwiki/kaliwiki#37]

**Comment by ThatEidolon** [comment]
Completed with Menu-Web-App branch

**Comment by ThatEidolon** [comment]
meant to comment, not close

This was completed with https://github.com/pwnwiki/kaliwiki/commit/3884342298dd1fe1def9486b35df098de893dcaa and https://github.com/pwnwiki/kaliwiki/commit/fc961a58bb92c27957caf97ea0d6ebaf61e06074

**Comment by ThatEidolon** [comment]
Closed with #86
