### ISSUE TITLE
Migrate KaliWiki to using gh-pages and CNAME domain

### ISSUE THREAD

**Issue by mubix** [pwnwiki/kaliwiki#78]
Basically what needs to happen is the master branch gets destroyed after making a clone of it to a "gh-pages" branch, then all commits go there instead of master, then we make a CNAME file that points kali.pwnwiki.io to the gh pages branch..

If you agree with the move and understand what needs to happen please comment on this and we'll get started after we have a consensus.

**Comment by ThatEidolon** [comment]
Sounds good to me.

I just created the branch.

**Comment by mubix** [comment]
I have changed the default branch to gh-pages

**Comment by ThatEidolon** [comment]
I'm going to let you delete the master branch once you feel like we have consensus

**Comment by giga1699** [comment]
Make it so!

**Comment by ThatEidolon** [comment]
woah, giga is back!

**Comment by mubix** [comment]
Don't forget this means you local copies need to be set to push and pull gh-pages too...

BTW: this works now too: http://pwnwiki.io/kaliwiki

**Comment by ThatEidolon** [comment]
thanks for the reminder mubix, all the branches should behave as normal though, correct?

I'm going to delete master now.

**Comment by mubix** [comment]
Master is officially gone on the repo

**Comment by ThatEidolon** [comment]
perfect. Thanks again for your help @mubix and @WebBreacher

**Comment by WebBreacher** [comment]
lol...all i did was drink a beer and watch you guys do the work. ah...management.

**Comment by WebBreacher** [comment]
Rob is making the http://kali.pwnwiki.io/ domain for this. Once the site is up there (he is working the DNS now) we'll close this.

**Comment by mubix** [comment]
Done and dusted, closing out.
